CREATE OR REPLACE VIEW osm_poi_type_2014 as  
select 
timeslice,
coords, 
planungsraum,
node_id,
last_modification_userid,
last_modification_time,
last_modification_version,
last_modification_changesetid,
name,
description, 
addr_city, 
addr_country, 
addr_housenumber, 
addr_postcode, 
addr_street, 
addr_suburb,
case
WHEN tourism LIKE 'hostel' THEN 'Hostel'
WHEN tourism LIKE 'hotel' THEN 'Hotel'
WHEN tourism LIKE 'guest_house' THEN 'Sonstige'
WHEN tourism LIKE 'apartment' THEN 'Sonstige'
WHEN tourism LIKE 'motel' THEN 'Sonstige'
WHEN tourism LIKE 'artwork' THEN 'Kunstwerk'
WHEN amenity LIKE 'arts_centre' THEN 'Kunstzentrum'
WHEN tourism LIKE 'gallery' THEN 'Gallerie'
WHEN tourism LIKE 'information' THEN 'Info'
WHEN tourism LIKE 'museum' THEN 'Museum'
WHEN tourism LIKE 'viewpoint' THEN 'Aussichtspunkt'
WHEN tourism LIKE 'zoo' THEN 'Zoo'
WHEN sport LIKE 'swimming' THEN 'Schwimmen'
WHEN sport LIKE 'basketball' THEN 'Basketball'
WHEN sport LIKE 'soccer' THEN 'Fussball'
WHEN leisure = 'sports_centre' AND sport NOT like 'martial_arts' THEN 'Sportzentrum'
WHEN sport LIKE 'table_tennis' THEN 'Tischtennis'
WHEN leisure LIKE 'sauna' THEN 'Sauna'
WHEN sport LIKE 'tennis' THEN 'Tennis'
WHEN sport LIKE 'martial_arts' THEN 'Kampfsport'
WHEN leisure LIKE 'fitness_centre' THEN 'Fitnesszentrum'
WHEN leisure LIKE 'playground' THEN 'Spielplatz'
WHEN leisure LIKE 'marina' THEN 'Wassersport'
WHEN leisure LIKE 'adult_gaming_centre' THEN 'Spielothek'
WHEN sport IS NOT NULL AND sport NOT IN 
('swimming',
'basketball',
'soccer',
'table_tennis',
'tennis',
'martial_arts') 
THEN 'Sonstige Sportarten'
WHEN amenity LIKE 'casino' THEN 'Spielothek'
WHEN amenity LIKE 'kindergarten' THEN 'Kindergarten'
WHEN office IS NOT NULL THEN 'Buero'
WHEN amenity LIKE 'fuel' THEN 'Tankstelle'
WHEN amenity LIKE 'coworking_space' THEN 'Coworking-Space'
WHEN amenity LIKE 'university' THEN 'Universitaet'
WHEN amenity LIKE 'gambling' THEN 'Spielothek'
WHEN amenity LIKE 'police' THEN 'Poilzei'
WHEN amenity LIKE 'fire_station' THEN 'Feuerwehr'
WHEN amenity LIKE 'childcare' THEN 'KiTa'
WHEN amenity LIKE 'college' THEN 'Hoehere Schule'
WHEN amenity LIKE 'marketplace' THEN 'Wochenmarkt'
WHEN amenity LIKE 'cinema' THEN 'Kino'
WHEN amenity LIKE 'biergarten' THEN 'Biergarten'
WHEN amenity LIKE 'car_rental' THEN 'Autovermietung'
WHEN amenity LIKE 'library' THEN 'Buecherei'
WHEN amenity LIKE 'community_centre' THEN 'Nachbarschaftszentrum'
WHEN amenity LIKE 'theatre' THEN 'Theater'
WHEN amenity LIKE 'ice_cream' THEN 'Eisdiele'
WHEN amenity LIKE 'nightclub' THEN 'Nachtclub'
WHEN amenity = 'place_of_worship' AND religion  like 'christian' THEN 'Kirche'
WHEN amenity = 'place_of_worship' AND religion  like 'muslim' THEN 'Moschee'
WHEN amenity LIKE 'place_of_worship' AND religion NOT IN 
('christian',
'muslim') 
THEN 'Sonstige Tempel'
WHEN amenity LIKE 'school' THEN 'Schule'
WHEN amenity LIKE 'brothel' THEN 'Bordell'
WHEN amenity LIKE 'post_office' THEN 'Post Filiale'
WHEN amenity LIKE 'social_facility' THEN 'Sozialeinrichtung'
WHEN amenity LIKE 'charging_station' THEN 'Ladestation'
WHEN amenity LIKE 'dentist' THEN 'Zahnarzt'
WHEN amenity LIKE 'bicycle_rental' THEN 'Fahrradverleih'
WHEN amenity LIKE 'driving_school' THEN 'Fahrschule'
WHEN amenity LIKE 'veterinary' THEN 'Tierarzt'
WHEN amenity LIKE 'embassy' THEN 'Botschaft'
WHEN amenity LIKE 'taxi' THEN 'Taxistand'
WHEN amenity LIKE 'toilets' THEN 'WC'
WHEN amenity LIKE 'bank' THEN 'Bankfiliale'
WHEN amenity LIKE 'doctors' THEN 'Arzt'
WHEN amenity LIKE 'parking' THEN 'Parkplatz'
WHEN amenity LIKE 'bar' THEN 'Bar'
WHEN amenity LIKE 'pharmacy' THEN 'Apotheke'
WHEN amenity LIKE 'pub' THEN 'Pub'
WHEN amenity LIKE 'telephone' THEN 'Telefon'
WHEN amenity = 'cafe' AND cuisine  like 'ice_cream' THEN 'Eisdiele'
WHEN amenity = 'cafe' AND cuisine  like 'coffee_shop' THEN 'Kaffee'
WHEN amenity LIKE 'cafe' AND cuisine NOT IN 
('ice_cream',
'coffee_shop') 
THEN 'Sonstige Cafes'
WHEN amenity LIKE 'bicycle_parking' THEN 'Fahrrad Parkplatz'
WHEN amenity LIKE 'waste_basket' THEN 'Muelleimer'
WHEN amenity LIKE 'bench' THEN 'Parkbank'
WHEN amenity LIKE 'hospital' THEN 'Krankenhaus'
WHEN amenity LIKE 'clinic' THEN 'Klinik'
WHEN amenity LIKE 'atm' THEN 'Geldautomat'
WHEN atm LIKE 'yes' THEN 'Geldautomat'
WHEN amenity LIKE 'post_box' THEN 'Briefkasten'
WHEN landuse LIKE 'cemetery' THEN 'Friedhof'
WHEN amenity LIKE 'music_school' THEN 'Musikschule'
WHEN amenity = 'vending_machine' AND vending  like 'parcel_pickup;parcel_mail_in' THEN 'Paketautomat'
WHEN amenity LIKE 'vending_machine' AND vending NOT IN 
('parcel_pickup;parcel_mail_in',
'public_transport_tickets',
'parking_tickets',
'excrement_bags',
'cigarettes',
'sweets',
'stamps',
'condoms',
'drinks;sweets',
'drinks') 
THEN 'Sonstige Automaten'
WHEN amenity = 'vending_machine' AND vending  like 'public_transport_tickets' THEN 'Fahrscheinautomat'
WHEN amenity = 'vending_machine' AND vending  like 'parking_tickets' THEN 'Parkticketautomat'
WHEN amenity = 'vending_machine' AND vending  like 'excrement_bags' THEN 'Kotbeutelautomat'
WHEN amenity = 'vending_machine' AND vending  like 'cigarettes' THEN 'Zigarettenautomat'
WHEN amenity = 'vending_machine' AND vending  like 'sweets' THEN 'Suessigkeitenautomat'
WHEN amenity = 'vending_machine' AND vending  like 'stamps' THEN 'Briefmarkenautomat'
WHEN amenity = 'vending_machine' AND vending  like 'condoms' THEN 'Kondomautomat'
WHEN amenity = 'vending_machine' AND vending  like 'drinks;sweets' THEN 'Getraenke und Suessigkeitenautomat'
WHEN amenity = 'vending_machine' AND vending  like 'drinks' THEN 'Getraenkeautomat'
WHEN amenity LIKE 'bbq' THEN 'Grillplatz'
WHEN amenity LIKE 'recycling' AND recycling LIKE 'clothes' THEN 'Glascontainer'
WHEN amenity LIKE 'recycling' AND recycling LIKE 'glass' THEN 'Glas- und Kleidungscontainer'
WHEN amenity LIKE 'recycling' AND recycling LIKE 'glass_clothes' THEN 'Kleidungscontainer'
WHEN amenity LIKE 'recycling' AND recycling not in ('clothes','glass','glass_clothes') THEN 'Sonstige Container'
WHEN amenity = 'restaurant' AND cuisine  like 'italian' THEN 'Restaurant Italiener'
WHEN amenity = 'restaurant' AND cuisine  like 'pizza' THEN 'Restaurant Italiener'
WHEN amenity = 'restaurant' AND cuisine  like 'mediterranean' THEN 'Restaurant Italiener'
WHEN amenity = 'restaurant' AND cuisine  like 'german' THEN 'Restaurant Deutsch'
WHEN amenity = 'restaurant' AND cuisine  like 'regional' THEN 'Restaurant Deutsch'
WHEN amenity = 'restaurant' AND cuisine  like 'indian' THEN 'Restaurant Indisch'
WHEN amenity = 'restaurant' AND cuisine  like 'asian' THEN 'Restaurant Asiatisch'
WHEN amenity = 'restaurant' AND cuisine  like 'vietnamese' THEN 'Restaurant Asiatisch'
WHEN amenity = 'restaurant' AND cuisine  like 'chinese' THEN 'Restaurant Asiatisch'
WHEN amenity = 'restaurant' AND cuisine  like 'thai' THEN 'Restaurant Asiatisch'
WHEN amenity = 'restaurant' AND cuisine  like 'korean' THEN 'Restaurant Asiatisch'
WHEN amenity = 'restaurant' AND cuisine  like 'sushi' THEN 'Restaurant Sushi'
WHEN amenity = 'restaurant' AND cuisine  like 'japanese' THEN 'Restaurant Sushi'
WHEN amenity = 'restaurant' AND cuisine  like 'greek' THEN 'Restaurant Griechisch'
WHEN amenity = 'restaurant' AND cuisine  like 'steak_house' THEN 'Restaurant Steakhouse'
WHEN amenity = 'restaurant' AND cuisine  like 'mexican' THEN 'Restaurant Steakhouse'
WHEN amenity = 'restaurant' AND cuisine  like 'burger' THEN 'Restaurant Steakhouse'
WHEN amenity = 'restaurant' AND cuisine  like 'international' THEN 'Restaurant International'
WHEN amenity = 'restaurant' AND cuisine  like 'french' THEN 'Restaurant International'
WHEN amenity = 'restaurant' AND cuisine  like 'spanish' THEN 'Restaurant International'
WHEN amenity = 'restaurant' AND cuisine  like 'turkish' THEN 'Restaurant Tuerkisch'
WHEN amenity = 'restaurant' AND cuisine  like 'kebab' THEN 'Restaurant Tuerkisch'
WHEN amenity = 'restaurant' AND cuisine  like 'arab' THEN 'Restaurant Tuerkisch'
WHEN amenity = 'restaurant' AND cuisine  like 'oriental' THEN 'Restaurant Tuerkisch'
WHEN amenity = 'fast_food' AND cuisine  like 'kebab' THEN 'Fastfood Kebap'
WHEN amenity = 'fast_food' AND cuisine  like 'turkish' THEN 'Fastfood Kebap'
WHEN amenity = 'fast_food' AND cuisine  like 'arab' THEN 'Fastfood Kebap'
WHEN amenity = 'fast_food' AND cuisine  like 'burger' THEN 'Fastfood Burger'
WHEN amenity = 'fast_food' AND cuisine  like 'asian' THEN 'Fastfood Asiatisch'
WHEN amenity = 'fast_food' AND cuisine  like 'chinese' THEN 'Fastfood Asiatisch'
WHEN amenity = 'fast_food' AND cuisine  like 'vietnamese' THEN 'Fastfood Asiatisch'
WHEN amenity = 'fast_food' AND cuisine  like 'thai' THEN 'Fastfood Asiatisch'
WHEN amenity = 'fast_food' AND cuisine  like 'sushi' THEN 'Fastfood Asiatisch'
WHEN amenity = 'fast_food' AND cuisine  like 'pizza' THEN 'Fastfood Pizza'
WHEN amenity = 'fast_food' AND cuisine  like 'italian' THEN 'Fastfood Pizza'
WHEN amenity = 'fast_food' AND cuisine  like 'german' THEN 'Fastfood Pommesbude'
WHEN amenity = 'fast_food' AND cuisine  like 'regional' THEN 'Fastfood Pommesbude'
WHEN amenity = 'fast_food' AND cuisine  like 'sausage' THEN 'Fastfood Pommesbude'
WHEN amenity LIKE 'fast_food' THEN 'fast_food Sonstiges'
WHEN amenity LIKE 'restaurant' THEN 'restaurant Sonstiges'
WHEN shop LIKE 'hairdresser' THEN 'Friseur'
WHEN shop LIKE 'bakery' THEN 'Baeckerei'
WHEN shop LIKE 'clothes' THEN 'Kleidung'
WHEN shop LIKE 'supermarket' THEN 'Supermarkt'
WHEN shop LIKE 'convenience' THEN 'Kiosk'
WHEN shop LIKE 'florist' THEN 'Florist'
WHEN shop LIKE 'kiosk' THEN 'Kiosk'
WHEN shop LIKE 'bicycle' THEN 'Fahrrad'
WHEN shop LIKE 'beauty' THEN 'Kosmetik und Beauty'
WHEN shop LIKE 'optician' THEN 'Optiker'
WHEN shop LIKE 'shoes' THEN 'Schuhe'
WHEN shop LIKE 'books' THEN 'Buecher'
WHEN shop LIKE 'massage' THEN 'Massage'
WHEN shop LIKE 'jewelry' THEN 'Schmuck'
WHEN shop LIKE 'car_repair' THEN 'Autoreperatur'
WHEN shop LIKE 'chemist' THEN 'Drogerie'
WHEN shop LIKE 'travel_agency' THEN 'Reisen'
WHEN shop LIKE 'mobile_phone' THEN 'Mobilfunk'
WHEN shop LIKE 'furniture' THEN 'Moebel'
WHEN shop LIKE 'beverages' THEN 'Getraenke'
WHEN shop LIKE 'deli' THEN 'Feinkost'
WHEN shop LIKE 'electronics' THEN 'Elektronik'
WHEN shop LIKE 'boutique' THEN 'Boutique'
WHEN shop LIKE 'car' THEN 'Autohaus'
WHEN shop LIKE 'alcohol' THEN 'Spirituosen'
WHEN shop LIKE 'gift' THEN 'Geschenke'
WHEN shop LIKE 'variety_store' THEN 'Postenmarkt'
WHEN shop LIKE 'butcher' THEN 'Schlachter'
WHEN shop LIKE 'laundry' THEN 'Waescherei'
WHEN shop LIKE 'computer' THEN 'Computer'
WHEN shop LIKE 'toys' THEN 'Spielzeug'
WHEN shop LIKE 'copyshop' THEN 'Copyshop'
WHEN shop LIKE 'tailor' THEN 'Schneider'
WHEN shop LIKE 'photo' THEN 'Foto'
WHEN shop LIKE 'art' THEN 'Kunst'
WHEN shop LIKE 'confectionery' THEN 'Suessigkeiten'
WHEN shop LIKE 'interior_decoration' THEN 'Dekoration'
WHEN shop LIKE 'dry_cleaning' THEN 'Reinigung'
WHEN shop LIKE 'greengrocer' THEN 'Feinkost'
WHEN shop LIKE 'funeral_directors' THEN 'Beerdigung'
WHEN shop LIKE 'sports' THEN 'Sport'
WHEN shop LIKE 'pet' THEN 'Zoofachgeschaeft'
WHEN shop LIKE 'fabric' THEN 'Textilgeschaeft'
WHEN shop LIKE 'hearing_aids' THEN 'Hoergeraete'
WHEN shop LIKE 'doityourself' THEN 'Baumarkt'
WHEN shop LIKE 'vacant' THEN 'Leerstand'
WHEN shop LIKE 'medical_supply' THEN 'Medical'
WHEN shop LIKE 'second_hand' THEN 'Second Hand'
WHEN shop LIKE 'newsagent' THEN 'Zeitung'
WHEN shop LIKE 'hardware' THEN 'Eisenwarenhandlung'
WHEN shop LIKE 'cosmetics' THEN 'Drogerie'
WHEN shop LIKE 'department_store' THEN 'Supermarkt'
WHEN shop LIKE 'tattoo' THEN 'Kosmetik und Beauty'
WHEN shop LIKE 'perfumery' THEN 'Drogerie'
WHEN shop IS NOT NULL THEN  'Sonstiger Shop'
WHEN public_transport IS NOT NULL THEN  'Haltestelle'
WHEN amenity IS NOT NULL THEN  'Sonstiges Gebaeude'
WHEN landuse IS NOT NULL THEN  'Sonstiges Gelaende'
WHEN heritage LIKE '4' THEN 'Baudenkmal'
WHEN heritage IS NOT NULL THEN  'Sonstiges Denkmal'
WHEN tourism IS NOT NULL THEN  'Sonstiges Tourismus'
WHEN sport IS NOT NULL THEN  'Sonstiges Sport'
WHEN leisure IS NOT NULL THEN  'Sonstiges Erholung'
end as poi_type
from osm_poi_2014 o;